name: Validate Terraform with Checkov, TFLint and Sonarqube

on:
  workflow_call:
    secrets:
      sonar_token:
        required: true
      sonar_host_url:
        required: true
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write
  actions: read
  security-events: write

jobs:
  RunTerraformValidation:
    name: Run Terraform SAST
    runs-on: ubuntu-latest
    env:
      TF_INPUT: "false"

    steps:
      - name: Clone the Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.9.0

      - name: terraform init (no backend)
        run: terraform init -backend=false

#      - name: Terraform tests
#        run: terraform test -no-color

      - name: terraform validate
        run: terraform validate

      - name: Terraform Format
        run: terraform fmt -check -recursive
      
      - name: TFLint
        id: lint
        if: success() || failure()
        uses: UKHomeOffice/core-cloud-workflow-tflint-scan@main

  sonarqube-scanner:
      uses: UKHomeOffice/core-cloud-workflow-sonarqube-scan/.github/workflows/sonarqube-scan.yaml@1.1.6
      secrets:
        sonar_token: ${{ secrets.sonar_token }}
        sonar_host_url: ${{ secrets.sonar_host_url }}

  checkov-scan:
      uses: UKHomeOffice/core-cloud-workflow-checkov-sast-scan/.github/workflows/checkov-scan-base.yaml@1.9.0

