name: Regular Terraform init and validate

on:
  schedule:
    - cron: "0 10 * * 3"   # runs every Wednesday at 10:00 AM 

permissions:
  contents: read
  id-token: write

jobs:
  RunTerraformInitValidate:
    name: Run Terraform Init and Validate
    runs-on: ubuntu-latest

    steps:
      - name: Clone the Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.9.0

      - name: terraform init (no backend)
        run: terraform init -backend=false

      - name: terraform validate
        run: terraform validate